# Generated by Django 4.2.7 on 2023-11-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
